# Default values for athena.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: alexismtr/athena
  pullPolicy: IfNotPresent
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: false
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  annotations: {}
  hosts: []
  tls: []

resources: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

dapr:
  enabled: true
  extraAnnotations:
  app:
    port: 3001
  metrics:
    port: 9090
  log:
    json: false
    level: info
  components:
    # rabbitmq:
    #   spec: |
    #     apiVersion: dapr.io/v1alpha1
    #     kind: Component
    #     metadata:
    #       name: {{ .Values.configuration.pubSub.dapr.pubComponentName }}
    #       namespace: {{ .Release.Namespace }}
    #     spec:
    #       type: pubsub.rabbitmq
    #       version: v1
    #       metadata: # configure depend on implementation

configuration:
  azFunction:
    runtime: dotnet
    extensionVersion: ~4
    environment: Development
    storageAccount:
      # -- set AZ_STORAGE key in the default secret
      connectionString: ""
      # -- use an already defined secret with AZ_STORAGE key
      secretRef:
    # -- enable / disable function at runtime
    functions:
      TelemetriesHttp:
        disabled: true
      TelemetriesEvent:
        disabled: true
      DaprEvent:
        disabled: true

  sqlServer:
    # -- set DB_CONNECTION_STRING key in the default secret
    connectionString:
      ""
      # -- use an already defined secret with DB_CONNECTION_STRING key
    secretRef:

  pubSub:
    topics:
      publish: ""
      subscribe: ""
    dapr:
      pubComponentName: ""
      subComponentName: ""
    brokers:
      publish:
        # -- set EVT_PUB_CONNECTION_STRING key in the default secret
        connectionString: ""
        # -- use an already defined secret with EVT_PUB_CONNECTION_STRING key
        secretRef:
      subscribe:
        # -- set EVT_SUB_CONNECTION_STRING key in the default secret
        connectionString: ""
        # -- use an already defined secret with EVT_SUB_CONNECTION_STRING key
        secretRef:

extraEnv: []
