# Default values for athena.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: alexismtr/athena
  pullPolicy: IfNotPresent
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: false
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  annotations: {}
  hosts: []
  tls: []

resources: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

environments:
  FUNCTIONS_WORKER_RUNTIME: dotnet
  FUNCTIONS_EXTENSION_VERSION: ~3
  AZURE_FUNCTIONS_ENVIRONMENT: Production
  EventPublish: new_computed_telemetries
  EventSubscribe: new_telemetries

environmentSecrets:
  AZ_STORAGE: "" # must be secret 
  EVT_SUB_CONNECTION_STRING: "" # must be secret
  EVT_PUB_CONNECTION_STRING: "" # must be secret
  DB_CONNECTION_STRING: "" # must be secret