{{- if empty .Values.existingEnvSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-%s" (include "athena.name" .) "secret-env" }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "athena.name" . }}
    helm.sh/chart: {{ include "athena.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  AZ_STORAGE: {{ default "" .Values.configuration.azFunction.storageAccount.connectionString | b64enc | quote }}
  DB_CONNECTION_STRING: {{ default "" .Values.configuration.sqlServer.dbConnectionString | b64enc | quote }}
  EVT_SUB_CONNECTION_STRING: {{ default "" .Values.configuration.pubSub.brokers.subscribe.connectionString | b64enc | quote }}
  EVT_PUB_CONNECTION_STRING: {{ default "" .Values.configuration.pubSub.brokers.publish.connectionString | b64enc | quote }}
{{- end -}}