apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-%s" (include "athena.name" .) "secret-env" }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "athena.name" . }}
    helm.sh/chart: {{ include "athena.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Secret
data:
  AZ_STORAGE: {{ .Values.environmentsSecret.connectionStrings.azStorage }}
  EVT_SUB_CONNECTION_STRING: {{ .Values.environmentsSecret.connectionStrings.publishBroker }}
  EVT_PUB_CONNECTION_STRING: {{ .Values.environmentsSecret.connectionStrings.subscribeBroker }}
  DB_CONNECTION_STRING: {{ .Values.environmentsSecret.connectionStrings.sqlServer }}