name: Notify new Helm Chart

on:
  push:
    tags:
    - 'helm-*'

jobs:
  notify_helm_repo:
    name: Notify Helm Repo
    runs-on: ubuntu-latest
    steps:
    - name: Repository Dispatch
      uses: peter-evans/repository-dispatch@v1
      with:
        token: ${{ secrets.PAT_GITHUB }}
        repository: AlexisMtr/poseidon-helm-chart
        event-type: chart-available
        client_payload: '{ "chart_repository": "${{ github.repository }}", "chart_path": "deploy/helm/athena" }'