name: Main

on:
  push:
    branches:
    - master

jobs:
  release:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    name: Semantic
    runs-on: ubuntu-20.04
    steps:
    - name: Install zsh
      run: sudo apt install zsh

    - name: Checkout
      uses: actions/checkout@v2
      with:
        # persist-credentials: false
        fetch-depth: 0
      
    - uses: actions/setup-node@v2.1.4
      with:
        node-version: 14
        
    - name: 'Install semantic-release'
      if: "!contains(github.ref, 'main')"
      run: |
        npm i -g semantic-release  \
          semantic-release-monorepo \
          @semantic-release/commit-analyzer \
          @semantic-release/release-notes-generator \
          semantic-release-helm \
          @semantic-release/changelog \
          @semantic-release/github \
          @semantic-release/git \
          @semantic-release/exec

    - name: 'release'
      id: release
      env:
        GITHUB_TOKEN: ${{ secrets.PAT_GITHUB }}
      run: |
        sudo chmod u+x -R .github/workflows/scripts/
        
        # Release Application fist
        cd ./src/ && npx semantic-release -e semantic-release-monorepo
        cd ..
        
        # Release other packages
        find . -name "package.json" -type f -not -path "./src/*" | xargs dirname | \
        xargs -I@ bash -c 'cd $PWD/@ && echo @ && npx semantic-release -e semantic-release-monorepo && sleep 1'